branches:
  only:
  - master
script: wget http://ocean.nationalgeographic.com/exposure/core_media/ngphoto/image/83949_0_480x360.jpg

deploy:
  provider: releases
  api_key:
    secure: 3OdLnZieUjfH9YB9bBKv0LnspG/ZFvc3LTvZ5Tqh5V5OByIfwd4+XaSZWS+3nJmnWaiHm+Cey6l+ClsHgcKqieU+G7WqGFKACVCK1j7z9Ad/IMLlqUUW6vuECErm9Sze7JojooIP97tECgJhSHKqskwFOWlVlHWmmdtxpjZxLbj9ZTkKp2osVGeTXN0JhnnsTmXO5UesBLB4IittIahWpUO65JJ5Jq7L0rOzKmV07s1JyuN+SlsO6RMiioSgyD6585tt+JU8zc0e0BNchE7Y9ujY82RECHT/N0YkVPrwDQnoxqUn2ALTbXXy5dLFYQChV6Jw/hNjKslfDzz4nhqnQdOB5UItNuJsGgIfxiLANlRZ4LiUn5BIyjRLg7bciS4GP7ivChlKcrH8K6p6XhJUvCRV+FzBHHibVBfhv1hMeRSFEVe0/TLc7YPBAJM+Rsm1jQC0qK+S0FPklwyEgTYESPuFUrUZK8aqGlQPml++h/QgP1tl18vbO6lxj4ESnKoKdX4xYInU+UwIMB9f6VuuSK+kM+nR7pqhUW1hOa9ovwd/a3V8204WWhLOS7qIf96v5WzrF3hH5CtqPuI7KQztecpLKfF5b2HvEivvK6WQWraeqw8b6QYN0K6IhIhLaPtI/P1qSC78iJxazuGCQjaQV6XRqlh7Dk6eS34kmJgYBTk=
  file: "83949_0_480x360.jpg"
  on:
    tags: true
